const notificationSeed = [
  {
    id: 1,
    title: 'Asset assigned',
    message: 'Asset AF-0002 was assigned to Priya Sharma.',
    timestamp: '2026-07-12T09:15:00',
    type: 'ASSET_ASSIGNED',
    relatedEntityType: 'asset_allocations',
    relatedEntityId: 1,
    isRead: false,
    roles: ['Admin', 'AssetManager', 'DepartmentHead', 'Employee'],
  },
  {
    id: 2,
    title: 'Maintenance approved',
    message: 'Your maintenance request for AF-0004 was approved.',
    timestamp: '2026-07-11T16:40:00',
    type: 'MAINTENANCE_APPROVED',
    relatedEntityType: 'maintenance_requests',
    relatedEntityId: 1,
    isRead: false,
    roles: ['Admin', 'AssetManager', 'DepartmentHead', 'Employee'],
  },
  {
    id: 3,
    title: 'Transfer requested',
    message: 'A transfer request for laptop AF-0018 is awaiting approval.',
    timestamp: '2026-07-10T11:20:00',
    type: 'TRANSFER_REQUESTED',
    relatedEntityType: 'transfer_requests',
    relatedEntityId: 4,
    isRead: true,
    roles: ['Admin', 'AssetManager'],
  },
  {
    id: 4,
    title: 'Booking reminder',
    message: 'Conference Room A booking starts in 30 minutes.',
    timestamp: '2026-07-10T08:50:00',
    type: 'BOOKING_REMINDER',
    relatedEntityType: 'bookings',
    relatedEntityId: 3,
    isRead: true,
    roles: ['Admin', 'DepartmentHead', 'Employee'],
  },
];

const activitySeed = [
  {
    id: 101,
    actor: 'Admin User',
    role: 'Admin',
    action: 'ASSET_REGISTERED',
    entity: 'Assets',
    description: 'Registered new laptop AF-0001 in the inventory directory.',
    timestamp: '2026-07-12T09:15:00',
    relatedEntityType: 'assets',
    relatedEntityId: 1,
    roles: ['Admin'],
  },
  {
    id: 102,
    actor: 'Priya Sharma',
    role: 'AssetManager',
    action: 'ASSET_ALLOCATED',
    entity: 'Allocations',
    description: 'Assigned asset AF-0002 to Priya Sharma for project rollout.',
    timestamp: '2026-07-12T08:42:00',
    relatedEntityType: 'asset_allocations',
    relatedEntityId: 2,
    roles: ['Admin', 'AssetManager'],
  },
  {
    id: 103,
    actor: 'Vikram Singh',
    role: 'DepartmentHead',
    action: 'MAINTENANCE_APPROVED',
    entity: 'Maintenance',
    description: 'Approved the maintenance request for AF-0004.',
    timestamp: '2026-07-11T16:40:00',
    relatedEntityType: 'maintenance_requests',
    relatedEntityId: 1,
    roles: ['Admin', 'AssetManager', 'DepartmentHead'],
  },
  {
    id: 104,
    actor: 'Anita Desai',
    role: 'Employee',
    action: 'BOOKING_CREATED',
    entity: 'Bookings',
    description: 'Created a booking for Conference Room A from 2:00 PM to 4:00 PM.',
    timestamp: '2026-07-10T11:25:00',
    relatedEntityType: 'bookings',
    relatedEntityId: 3,
    roles: ['Admin', 'AssetManager', 'DepartmentHead', 'Employee'],
  },
  {
    id: 105,
    actor: 'Rohan Iyer',
    role: 'AssetManager',
    action: 'AUDIT_CLOSED',
    entity: 'Audits',
    description: 'Closed the quarterly audit cycle for the office asset inventory.',
    timestamp: '2026-07-09T14:00:00',
    relatedEntityType: 'audit_cycles',
    relatedEntityId: 7,
    roles: ['Admin', 'AssetManager'],
  },
];

export function getMockActivityData(userRole = 'Employee') {
  const visibleNotifications = notificationSeed.filter((item) => item.roles.includes(userRole));
  const visibleActivityLogs = activitySeed.filter((item) => item.roles.includes(userRole));

  return {
    notifications: visibleNotifications,
    activityLogs: visibleActivityLogs,
  };
}
